### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by llagerlof** [goniszewski/grimoire#50] opened 2024-01-23 13:34 UTC
**Describe the bug**
The application starts itself without errors after `docker-compose up`:

```
$ docker-compose up
[+] Building 0.0s (0/0)
[+] Running 2/0
 ✔ Container grimoire-pocketbase  Created
 ✔ Container grimoire             Created
Attaching to grimoire, grimoire-pocketbase
grimoire-pocketbase  | 2024/01/23 13:15:19 Server started at http://0.0.0.0:80
grimoire-pocketbase  | ├─ REST API: http://0.0.0.0:80/api/
grimoire-pocketbase  | └─ Admin UI: http://0.0.0.0:80/_/
grimoire             | Listening on 0.0.0.0:5173
```

But when I try to access `http://localhost:5173` I receive an error 500. The console shows an error in loop:

```
grimoire             | ClientResponseError 0: The request was autocancelled. You can find more info in https://github.com/pocketbase/js-sdk#auto-cancellation.
grimoire             |     at file:///app/node_modules/.pnpm/pocketbase@0.19.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:31144
grimoire             |     at async load (file:///app/build/server/chunks/0-546e495e.js:32:24)
grimoire             |     at async load_server_data (file:///app/build/server/index.js:1186:18)
grimoire             |     at async file:///app/build/server/index.js:2557:18 {
grimoire             |   url: '',
grimoire             |   status: 0,
grimoire             |   response: {},
grimoire             |   isAbort: true,
grimoire             |   originalError: DOMException [AbortError]: This operation was aborted
grimoire             |       at fetch (file:///app/build/shims.js:20346:13)
grimoire             |       at async load (file:///app/build/server/chunks/0-546e495e.js:32:24)
grimoire             |       at async load_server_data (file:///app/build/server/index.js:1186:18)
grimoire             |       at async file:///app/build/server/index.js:2557:18
grimoire             | }
grimoire             | ClientResponseError 0: The request was autocancelled. You can find more info in https://github.com/pocketbase/js-sdk#auto-cancellation.
grimoire             |     at file:///app/node_modules/.pnpm/pocketbase@0.19.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:31144
grimoire             |     at async load (file:///app/build/server/chunks/0-546e495e.js:32:24)
grimoire             |     at async load_server_data (file:///app/build/server/index.js:1186:18)
grimoire             |     at async respond_with_error (file:///app/build/server/index.js:2215:27)
grimoire             |     at async resolve (file:///app/build/server/index.js:3573:16)
grimoire             |     at async Object.handle (file:///app/build/server/chunks/hooks.server-6da8a1ec.js:31:20)
grimoire             |     at async respond (file:///app/build/server/index.js:3404:22)
grimoire             |     at async Array.ssr (file:///app/build/handler.js:1221:3) {
grimoire             |   url: '',
grimoire             |   status: 0,
grimoire             |   response: {},
grimoire             |   isAbort: true,
grimoire             |   originalError: DOMException [AbortError]: This operation was aborted
grimoire             |       at fetch (file:///app/build/shims.js:20346:13)
grimoire             |       at async load (file:///app/build/server/chunks/0-546e495e.js:32:24)
grimoire             |       at async load_server_data (file:///app/build/server/index.js:1186:18)
grimoire             |       at async respond_with_error (file:///app/build/server/index.js:2215:27)
grimoire             |       at async resolve (file:///app/build/server/index.js:3573:16)

<continues forever>
```

**To Reproduce**
1. git clone https://github.com/goniszewski/grimoire
2. cd grimoire
3. docker-compose up
4. Try to access http://localhost:5173

**Expected behavior**
The web application should not return an error 500.

**Desktop (please complete the following information):**
 - OS: WSL 2 openSUSE running on Windows 11
 - Browser Firefox
 - Version 121

**Additional context**
I already have other docker containers running without problems in my WSL.

This is my `.env`:

```
# Set it if you're using external PocketBase installation (default: http://localhost:8090)
# Example: PUBLIC_POCKETBASE_URL=https://grimoire.mydomain.com:8090
PUBLIC_POCKETBASE_URL=
# RECOMMENDED: Change this to your email
ROOT_ADMIN_EMAIL=llagerlof@gmail.com
# RECOMMENDED: Use a secure password. Can be later changed in PocketBase's admin panel
ROOT_ADMIN_PASSWORD=123456
# Set this to your domain name (default: http://localhost:5173)
# Example: ORIGIN=grimoire.mydomain.com
ORIGIN=http://localhost:5173
# Set this to true if you're using HTTPS (default: false)
# Example: PUBLIC_HTTPS_ONLY=true
PUBLIC_HTTPS_ONLY=false
# Change to the port you want the app to listen on (default: 5173)
# Example: PORT=80
PORT=5173
# Set this to true if you want to disable public signups (default: false)
PUBLIC_SIGNUP_DISABLED=false
```

**Comment by goniszewski** [comment] 2024-01-24 09:36
Hello @llagerlof, thank you for taking the time to create this issue!

I believe it is a duplicate of [this one](https://github.com/goniszewski/grimoire/issues/49), so I will close your issue and mention you in my response to the original one.

**Closed by goniszewski** 2024-01-24 09:36 UTC
